name: "Infra Pipeline"

on: workflow_dispatch

jobs:
  terraform_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
          
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: # optional
          # ClientId of the Azure Service principal created.
          client-id: # optional
          # TenantId of the Azure Service principal created.
          tenant-id: # optional
          # Azure subscriptionId
          subscription-id: # optional
          # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
          enable-AzPSSession: # optional
          # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
          environment: # optional, default is azurecloud
          # Set this value to true to enable support for accessing tenants without subscriptions
          allow-no-subscriptions: # optional
          # Provide audience field for access-token. Default value is api://AzureADTokenExchange
          audience: # optional, default is api://AzureADTokenExchange
          # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
          auth-type: # optional, default is SERVICE_PRINCIPAL
          
          
      - name: Terraform init azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          # Azure Credentials in JSON format
          azure_credentials: 
          # State file location - resource group name
          resource_group_name: 
          # State file location - container name
          container_name: 
          # State file location - storage account name
          storage_account_name: 
          # State file location - file name
          file_name: # optional, default is terraform.tfstate
          # Subscription Id of the resource group
          subscription_id: # optional, default is empty
          # Terraform working directory
          tf_working_directory: # optional, default is .
